### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by ghost** [DoctorVanGogh/ModSwitch#5]
Hello, I found a strange bug.
When I make a physical copy of all my installed mods
from "Steam\steamapps\workshop\content\294100"
to "Steam\steamapps\common\RimWorld\Mods"
so I can prevent save corruption because of workshop autoupdate, your mod-manager double up on the mods in the list, even tho there is no duplicates in any of the actual folders
https://i.imgur.com/bfL3D9P.png (Image of it)

ModListBackup did not do this.

Edit: Its once you copied the mods and load a list, thats when the bug starts happening.
If you save a list, shutdown the game, make copies, start the game: there is no issue, its only once you've made the copies and try to load another list or reload the list you already have the duplication happens

**Comment by DoctorVanGogh** [comment]
Um yes... you have every mod available twice..... once from steam and once from the local copies... this is the expected result...

Just disable ModSwitch (both ones 😁 ) and see if the list still has double entries for everything.

If this in fact makes the duplicates disappear, please attach your `C:\Users\[Username]\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config\Mod_1139051045_ModSwitch.xml`file so I can check if your configuration might have gotten mixed up.

**Comment by ghost** [comment]
No. ModListBackup did not do this.
Look at these pictures:
https://i.imgur.com/5OpcB0E.png
https://i.imgur.com/eZI3gUy.png

Rimworld by iself is smart enough to see the difference of a physical copy and a workshop copy and automatically pick the physical copy over the workshop copy. As I said the bug only occurs when you copy the mods THEN try and load another modlist. otherwise the duplication does not happen.

So if we look at the pictures you can see that the client knows that it should load the physical copy UNTIL i load a saved list (with the mods already copied)
https://i.imgur.com/bfL3D9P.png <---- Load any list AFTER copy

Edit: It seems that I can't attach the file, its not supported. But ill make a before and after picture

https://i.imgur.com/PbE6rw0.png (Picture of xml config when not experience duplicates)
https://i.imgur.com/FUD5Asl.png (Picture of xml cofig WITH duplicates)

I believe its not the list itself, somehow once the mod has both a physical copy and a workshop copy it has a hard time deciding what to load once you call the function for loading a list.

When I experience the duplicates I can still add more mods and they dont show up as duplicates and I can also disable one of the duplicates.

**Comment by DoctorVanGogh** [comment]
well... then stuff the file inside a zip please...

https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by ghost** [comment]
Sorry
[Mod_1139051045_ModSwitch.zip](https://github.com/DoctorVanGogh/ModSwitch/files/1364088/Mod_1139051045_ModSwitch.zip)

**Comment by DoctorVanGogh** [comment]
That can't be it... there is not a single non-steam mod in those sets...
Are you running a local version in parallel? If so, please just attach any `Mod_[something]_ModSwitch.xml` file from that directory 😉 

Are you even potentially running ModSwitch twice? Once from steam and once locally? I'd expect things to go very wrong then....

**Comment by ghost** [comment]
Okay so I am not running multiple rimworlds, only one. If i remove the physical copy (1139051045) from Steam\steamapps\common\RimWorld\Mods and keep it in the workshop folder, duplicates still occurs and only when loading a list. The issue is when selecting to load a list, that is when the mod has a hard time to difference between physical and workshop.

Notice that I dont copy my mods with your mod, I do it myself since its faster. I copy all folders from workshop and paste them to regular mod folder.

Edit: Interesting, if you "apply a mod list" then press "undo" then apply a mod list again
https://i.imgur.com/Wr9PCR1.png (this happends)

Work around right now is to make a mod list for current play-through and then copy mods then never touch the apply function and duplicates wont happend

**Comment by DoctorVanGogh** [comment]
Oh god... do *not* just copy the workshop contents over... I know ModSwitch at least gets confused by the mere numerical folder names and just assumes things come from steam, and things all go wonky from there...

**Comment by ghost** [comment]
I just thought I report it as a bug. Since Mod List Backup never had issues with this.

**Comment by DoctorVanGogh** [comment]
Yeah, thanks for the report... I'll see if I can 'unconfuse' ModSwitch in those edge cases... 

Still, my advice would be "Dont do that" ;)

Also... you could try copying your Mods with this tiny powershell script (it's not 100% tested or anything)..
```ps
function GetName($dir) {
    $about = (Join-Path $dir "About\About.xml")
    if (Test-Path $about) {
        return (Select-Xml -Path $about  -XPath "ModMetaData/name/text()" | Select-Object -ExpandProperty Node | Select-Object -ExpandProperty Value)
    } else {
        return "Local.{0}" -f $dir.Name
    }
}

function CopyMods($source, $target) {
    Get-ChildItem -Path $source | % { Copy-Item -Recurse -path $_ -destination (Join-Path $target (GetName($_))) }   
}
CopyMods "C:\Program Files (x86)\Steam\SteamApps\workshop\content\294100" "C:\Program Files (x86)\Steam\SteamApps\common\RimWorld\Mods"
```
